-- =============================================================================
-- ReservArte · CREACIÓN de la base de datos PostgreSQL (solo esquema, sin datos)
-- =============================================================================
-- FICHERO GENERADO desde las migraciones de EF Core. NO EDITAR A MANO.
-- Un cambio de base de datos se hace con una migración y después se regenera:
--   bash data/schema/regenerate-create.sh
--
-- Última migración incluida: 20260929161557_AddAppointmentCreatedBy
-- Idempotente: se puede ejecutar varias veces; crea la base solo si no existe y
-- salta las migraciones ya aplicadas gracias a __EFMigrationsHistory.
-- Uso (conectado a la base de mantenimiento «postgres»):
--   docker exec -i reservarte-pg psql -U reservarte -d postgres -v ON_ERROR_STOP=1 < data/schema/create_ReservArteDB.sql
-- Otra base (p. ej. una desechable): añadir -v db=nombre. Por defecto, reservarte.
-- Orden: 1) drop_ReservArteDB.sql (opcional, DESTRUYE)  2) este fichero
--        3) data/demo/seed_demo_ReservArteDB.sql (solo desarrollo). Detalle: data/README.md
-- =============================================================================

\if :{?db}
\else
\set db reservarte
\endif

SELECT format('CREATE DATABASE %I', :'db')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'db') \gexec

\connect :db

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "Organizations" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Subdomain" character varying(100) NOT NULL,
        "Email" character varying(255) NOT NULL,
        "Phone" character varying(20),
        "Address" character varying(300),
        "City" character varying(100),
        "PostalCode" character varying(10),
        "Country" character varying(2) NOT NULL DEFAULT 'ES',
        "TaxId" character varying(20),
        "LogoUrl" character varying(500),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "Rol" character varying(50) NOT NULL,
        "ProfileImageUrl" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "AcceptedTermsVersion" character varying(20),
        "AcceptedPrivacyVersion" character varying(20),
        "ConsentAcceptedAt" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUsers_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "ServiceCategories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "Color" character varying(20),
        "DisplayOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ServiceCategories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ServiceCategories_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "ServicePackages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "TotalPrice" numeric(10,2) NOT NULL,
        "DiscountPercentage" numeric(5,2) NOT NULL,
        "ImageUrl" character varying(500),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ServicePackages" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ServicePackages_DiscountPercentage" CHECK ("DiscountPercentage" >= 0 AND "DiscountPercentage" <= 100),
        CONSTRAINT "CK_ServicePackages_TotalPrice" CHECK ("TotalPrice" >= 0),
        CONSTRAINT "FK_ServicePackages_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "ProviderDisplayName" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("OrganizationId", "LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" integer NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "Customers" (
        "Id" integer NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "Email" character varying(255) NOT NULL,
        "Phone" character varying(20),
        "ProfileImageUrl" character varying(500),
        "BirthDate" date,
        "Category" character varying(20) NOT NULL,
        "LoyaltyPoints" integer NOT NULL,
        "IsBlocked" boolean NOT NULL,
        "BlockedReason" character varying(500),
        "PreferredContactMethod" character varying(20) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Customers_Category" CHECK ("Category" IN ('regular', 'vip', 'new')),
        CONSTRAINT "CK_Customers_EmailLowercase" CHECK ("Email" = lower("Email")),
        CONSTRAINT "CK_Customers_PreferredContactMethod" CHECK ("PreferredContactMethod" IN ('email', 'phone', 'sms', 'whatsapp')),
        CONSTRAINT "FK_Customers_AspNetUsers_Id" FOREIGN KEY ("Id") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Customers_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "Employees" (
        "Id" integer NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "Email" character varying(255) NOT NULL,
        "Phone" character varying(20),
        "Rol" character varying(50) NOT NULL,
        "ProfileImageUrl" character varying(500),
        "HireDate" date,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Employees_EmailLowercase" CHECK ("Email" = lower("Email")),
        CONSTRAINT "FK_Employees_AspNetUsers_Id" FOREIGN KEY ("Id") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Employees_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" integer NOT NULL,
        "Token" character varying(200) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "CreatedByIp" character varying(45),
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "Services" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "DurationMinutes" integer NOT NULL,
        "BasePrice" numeric(10,2) NOT NULL,
        "CategoryId" integer,
        "ImageUrl" character varying(500),
        "IsActive" boolean NOT NULL,
        "RequiresAllergyTest" boolean NOT NULL,
        "AllergyTestHoursBefore" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Services_DurationAndPrice" CHECK ("DurationMinutes" > 0 AND "BasePrice" >= 0),
        CONSTRAINT "FK_Services_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Services_ServiceCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ServiceCategories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "CustomerAllergies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "CustomerId" integer NOT NULL,
        "AllergyDescription" character varying(500) NOT NULL,
        "Severity" character varying(20) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_CustomerAllergies" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CustomerAllergies_Severity" CHECK ("Severity" IN ('low', 'medium', 'high')),
        CONSTRAINT "FK_CustomerAllergies_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CustomerAllergies_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "CustomerConsents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "CustomerId" integer NOT NULL,
        "ConsentType" character varying(50) NOT NULL,
        "IsGranted" boolean NOT NULL,
        "GrantedAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_CustomerConsents" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CustomerConsents_ConsentType" CHECK ("ConsentType" IN ('data_processing', 'marketing', 'photos', 'whatsapp', 'saved_cards')),
        CONSTRAINT "CK_CustomerConsents_GrantedAt" CHECK ("IsGranted" = FALSE OR "GrantedAt" IS NOT NULL),
        CONSTRAINT "FK_CustomerConsents_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CustomerConsents_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "Appointments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "CustomerId" integer NOT NULL,
        "EmployeeId" integer NOT NULL,
        "AppointmentDate" date NOT NULL,
        "StartTime" time NOT NULL,
        "EndTime" time NOT NULL,
        "Status" character varying(50) NOT NULL,
        "TotalPrice" numeric(10,2) NOT NULL,
        "DepositAmount" numeric(10,2) NOT NULL,
        "RedsysOrderNumber" character varying(20),
        "RedsysPreAuthToken" character varying(255),
        "CancellationReason" character varying(500),
        "CancelledAt" timestamp with time zone,
        "CancelledById" integer,
        "CancelledByType" character varying(20),
        "Notes" character varying(2000),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Appointments_Amounts" CHECK ("TotalPrice" >= 0 AND "DepositAmount" >= 0),
        CONSTRAINT "CK_Appointments_CancelledByType" CHECK ("CancelledByType" IN ('customer', 'business')),
        CONSTRAINT "CK_Appointments_EndTime" CHECK ("EndTime" > "StartTime"),
        CONSTRAINT "CK_Appointments_Status" CHECK ("Status" IN ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'cancelled_by_customer', 'cancelled_by_business', 'no_show')),
        CONSTRAINT "FK_Appointments_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Appointments_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Appointments_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "CustomerNotes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "CustomerId" integer NOT NULL,
        "EmployeeId" integer NOT NULL,
        "Note" character varying(2000) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_CustomerNotes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CustomerNotes_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CustomerNotes_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CustomerNotes_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "EmployeeAvailabilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "EmployeeId" integer NOT NULL,
        "DayOfWeek" integer NOT NULL,
        "StartTime" time NOT NULL,
        "EndTime" time NOT NULL,
        "IsRecurring" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_EmployeeAvailabilities" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_EmployeeAvailabilities_DayOfWeek" CHECK ("DayOfWeek" >= 0 AND "DayOfWeek" <= 6),
        CONSTRAINT "FK_EmployeeAvailabilities_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_EmployeeAvailabilities_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "EmployeeExceptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "EmployeeId" integer NOT NULL,
        "StartDateTime" timestamp with time zone NOT NULL,
        "EndDateTime" timestamp with time zone NOT NULL,
        "Reason" character varying(500),
        "Type" character varying(50) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_EmployeeExceptions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_EmployeeExceptions_Interval" CHECK ("EndDateTime" > "StartDateTime"),
        CONSTRAINT "CK_EmployeeExceptions_Type" CHECK ("Type" IN ('vacation', 'sick_leave', 'personal', 'training', 'other')),
        CONSTRAINT "FK_EmployeeExceptions_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_EmployeeExceptions_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "EmployeeServices" (
        "EmployeeId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "ProficiencyLevel" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_EmployeeServices" PRIMARY KEY ("EmployeeId", "ServiceId"),
        CONSTRAINT "CK_EmployeeServices_ProficiencyLevel" CHECK ("ProficiencyLevel" >= 1 AND "ProficiencyLevel" <= 5),
        CONSTRAINT "FK_EmployeeServices_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_EmployeeServices_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_EmployeeServices_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "ServicePackageItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "ServicePackageId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        "Order" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_ServicePackageItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ServicePackageItems_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ServicePackageItems_ServicePackages_ServicePackageId" FOREIGN KEY ("ServicePackageId") REFERENCES "ServicePackages" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ServicePackageItems_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "ServicePricings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "ServiceId" integer NOT NULL,
        "EmployeeLevel" character varying(20) NOT NULL,
        "Price" numeric(10,2) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ServicePricings" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ServicePricings_EmployeeLevel" CHECK ("EmployeeLevel" IN ('junior', 'senior', 'expert')),
        CONSTRAINT "CK_ServicePricings_Price" CHECK ("Price" >= 0),
        CONSTRAINT "FK_ServicePricings_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ServicePricings_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "ServiceVariations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "ServiceId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "PriceModifier" numeric(10,2) NOT NULL,
        "DurationModifier" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ServiceVariations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ServiceVariations_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ServiceVariations_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "WaitingLists" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "CustomerId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        "PreferredEmployeeId" integer,
        "PreferredDate" timestamp with time zone,
        "DateRangeStart" timestamp with time zone NOT NULL,
        "DateRangeEnd" timestamp with time zone NOT NULL,
        "Priority" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "NotifiedAt" timestamp with time zone,
        CONSTRAINT "PK_WaitingLists" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_WaitingLists_DateRange" CHECK ("DateRangeEnd" > "DateRangeStart"),
        CONSTRAINT "FK_WaitingLists_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_WaitingLists_Employees_PreferredEmployeeId" FOREIGN KEY ("PreferredEmployeeId") REFERENCES "Employees" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_WaitingLists_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_WaitingLists_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE TABLE "AppointmentServiceItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizationId" uuid NOT NULL,
        "AppointmentId" integer NOT NULL,
        "ServiceId" integer NOT NULL,
        "ServiceVariationId" integer,
        "Price" numeric(10,2) NOT NULL,
        "DurationMinutes" integer NOT NULL,
        "Order" integer NOT NULL,
        CONSTRAINT "PK_AppointmentServiceItems" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_AppointmentServiceItems_PriceAndDuration" CHECK ("Price" >= 0 AND "DurationMinutes" > 0),
        CONSTRAINT "FK_AppointmentServiceItems_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AppointmentServiceItems_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_AppointmentServiceItems_ServiceVariations_ServiceVariationId" FOREIGN KEY ("ServiceVariationId") REFERENCES "ServiceVariations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_AppointmentServiceItems_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX idx_appointments_org_date ON "Appointments" ("OrganizationId", "AppointmentDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX idx_appointments_redsys_order ON "Appointments" ("RedsysOrderNumber") WHERE "RedsysOrderNumber" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_Appointments_CustomerId" ON "Appointments" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_Appointments_EmployeeId_AppointmentDate" ON "Appointments" ("EmployeeId", "AppointmentDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_AppointmentServiceItems_AppointmentId_Order" ON "AppointmentServiceItems" ("AppointmentId", "Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_AppointmentServiceItems_OrganizationId" ON "AppointmentServiceItems" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_AppointmentServiceItems_ServiceId" ON "AppointmentServiceItems" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_AppointmentServiceItems_ServiceVariationId" ON "AppointmentServiceItems" ("ServiceVariationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "EmailIndex" ON "AspNetUsers" ("OrganizationId", "NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUsers_OrganizationId" ON "AspNetUsers" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("OrganizationId", "NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_CustomerAllergies_CustomerId" ON "CustomerAllergies" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_CustomerAllergies_OrganizationId" ON "CustomerAllergies" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CustomerConsents_CustomerId_ConsentType" ON "CustomerConsents" ("CustomerId", "ConsentType") WHERE "IsActive" = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_CustomerConsents_OrganizationId" ON "CustomerConsents" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_CustomerNotes_CustomerId_CreatedAt" ON "CustomerNotes" ("CustomerId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_CustomerNotes_EmployeeId" ON "CustomerNotes" ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_CustomerNotes_OrganizationId" ON "CustomerNotes" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Customers_OrganizationId_Email" ON "Customers" ("OrganizationId", "Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_EmployeeAvailabilities_EmployeeId_DayOfWeek" ON "EmployeeAvailabilities" ("EmployeeId", "DayOfWeek");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_EmployeeAvailabilities_OrganizationId" ON "EmployeeAvailabilities" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_EmployeeExceptions_EmployeeId_StartDateTime_EndDateTime" ON "EmployeeExceptions" ("EmployeeId", "StartDateTime", "EndDateTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_EmployeeExceptions_OrganizationId" ON "EmployeeExceptions" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Employees_OrganizationId_Email" ON "Employees" ("OrganizationId", "Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_EmployeeServices_OrganizationId" ON "EmployeeServices" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_EmployeeServices_ServiceId" ON "EmployeeServices" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Organizations_Subdomain" ON "Organizations" ("Subdomain");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServiceCategories_OrganizationId_DisplayOrder" ON "ServiceCategories" ("OrganizationId", "DisplayOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServicePackageItems_OrganizationId" ON "ServicePackageItems" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServicePackageItems_ServiceId" ON "ServicePackageItems" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServicePackageItems_ServicePackageId_Order" ON "ServicePackageItems" ("ServicePackageId", "Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServicePackages_OrganizationId" ON "ServicePackages" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServicePricings_OrganizationId" ON "ServicePricings" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ServicePricings_ServiceId_EmployeeLevel" ON "ServicePricings" ("ServiceId", "EmployeeLevel") WHERE "IsActive" = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_Services_CategoryId" ON "Services" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_Services_OrganizationId" ON "Services" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServiceVariations_OrganizationId" ON "ServiceVariations" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_ServiceVariations_ServiceId" ON "ServiceVariations" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX idx_waiting_lists_org_service_priority ON "WaitingLists" ("OrganizationId", "ServiceId", "Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_WaitingLists_CustomerId" ON "WaitingLists" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_WaitingLists_PreferredEmployeeId" ON "WaitingLists" ("PreferredEmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    CREATE INDEX "IX_WaitingLists_ServiceId" ON "WaitingLists" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929073713_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260929073713_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929161557_AddAppointmentCreatedBy') THEN
    ALTER TABLE "Appointments" ADD "CreatedById" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260929161557_AddAppointmentCreatedBy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260929161557_AddAppointmentCreatedBy', '10.0.12');
    END IF;
END $EF$;
COMMIT;

