-- =============================================================================
-- ReservArte · DATOS DEMO para desarrollo (PostgreSQL, solo datos: DML)
-- =============================================================================
-- ⚠ SOLO DESARROLLO: contraseñas conocidas. NUNCA ejecutar en producción.
--
-- Requisito: base creada con data/schema/create_ReservArteDB.sql.
-- Uso (conectado a la base de mantenimiento «postgres»; el script se conecta a la de destino):
--   docker exec -i reservarte-pg psql -U reservarte -d postgres -v ON_ERROR_STOP=1 < data/demo/seed_demo_ReservArteDB.sql
-- Otra base (p. ej. una desechable): añadir -v db=nombre. Por defecto, reservarte.
--
-- Idempotente: si ya existe alguna organización no inserta nada (mismo criterio
-- que DevSeeder). Todo va en una transacción: o entra entero o no entra nada.
--
-- Cuentas demo (las mismas que crea DevSeeder, con las mismas contraseñas):
--   guille@svalero.com              Admin1234!   Admin     (sin ficha de empleado)
--   maria.garcia@reservarte.com     Maria123!    Employee
--   lucia.martinez@reservarte.com   Lucia123!    Employee
--   carmen.lopez@example.com        Cliente123!  Customer  (ficha de clienta VIP)
--   sofia.ruiz@example.com          Cliente123!  Customer  (ficha de clienta)
--   takervare@gmail.com             (Google)     Admin     (sin contraseña local: entra con Google)
-- Los PasswordHash son del PasswordHasher de ASP.NET Core Identity (PBKDF2).
-- Los emails van en minúsculas: Customers y Employees lo exigen con un CHECK (H-37).
--
-- Mantenimiento: si una migración cambia una tabla que este script siembra, se
-- actualiza en el mismo PR. Ver data/README.md.
-- =============================================================================

\if :{?db}
\else
\set db reservarte
\endif
\connect :db
\set org 'AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE'

SELECT EXISTS (SELECT 1 FROM "Organizations") AS ya_sembrada \gset
\if :ya_sembrada
\echo Ya hay organizaciones en la base :db: no se insertan datos demo.
\else

BEGIN;

-- ── Organización ─────────────────────────────────────────────────────────────
INSERT INTO "Organizations" ("Id", "Name", "Subdomain", "Email", "Phone", "Country", "IsActive", "CreatedAt")
VALUES (:'org', 'More Than Brows', 'morethanbrows', 'info@morethanbrows.com', '+34600000000', 'ES', TRUE, now());

-- ── Configuración del centro (RA-869f74u7y) ──────────────────────────────────
-- Los mismos valores por defecto que escribe DevSeeder: zona de la península,
-- cancelación tardía por debajo de 24 h y bloqueo a las 3 no presentaciones.
INSERT INTO "OrganizationSettings" ("OrganizationId", "TimeZone", "CancellationHoursThreshold", "MaxNoShowsBeforeBlock", "CreatedAt")
VALUES (:'org', 'Europe/Madrid', 24, 3, now());

-- ── Recordatorio por defecto (RA-869d7f5zq) ──────────────────────────────────
-- El mismo que escribe DevSeeder: un email 24 h antes de la cita, entre las
-- 09:00 y las 21:00 (hora del centro), con su plantilla. E'' para los saltos de línea.
INSERT INTO "MessageTemplates" ("OrganizationId", "Name", "Type", "Subject", "Body", "Language", "IsActive", "CreatedAt")
VALUES (:'org', 'Recordatorio de cita', 'email_reminder',
        'Recordatorio de tu cita en {{organizationName}}',
        E'Hola, {{customerName}}:\n\nTe recordamos tu cita en {{organizationName}} el {{appointmentDate}} a las {{appointmentTime}} con {{employeeName}}.\n\nSi no puedes venir, avísanos con antelación. ¡Te esperamos!',
        'es', TRUE, now());

INSERT INTO "ReminderConfigurations" ("OrganizationId", "ReminderOrder", "HoursBeforeAppointment", "Channel", "IsActive", "MessageTemplateId", "AllowedSendStartTime", "AllowedSendEndTime", "CreatedAt")
SELECT :'org', 1, 24, 'email', TRUE, "Id", TIME '09:00', TIME '21:00', now()
FROM "MessageTemplates" WHERE "OrganizationId" = :'org' AND "Name" = 'Recordatorio de cita';

-- ── Cuentas de acceso (AspNetUsers) ──────────────────────────────────────────
-- Ids explícitos: la ficha de empleado y la de clienta comparten el Id de su cuenta.
-- La columna es GENERATED BY DEFAULT AS IDENTITY: admite el Id explícito, y la
-- secuencia se avanza al final (setval) para que las altas de la API no choquen.
INSERT INTO "AspNetUsers" (
    "Id", "OrganizationId", "FirstName", "LastName", "Email", "NormalizedEmail", "UserName", "NormalizedUserName",
    "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed",
    "TwoFactorEnabled", "LockoutEnabled", "AccessFailedCount", "Rol", "CreatedAt")
VALUES
    (1, :'org', 'Guillermo', 'Admin', 'guille@svalero.com', 'GUILLE@SVALERO.COM', 'guille@svalero.com', 'GUILLE@SVALERO.COM', TRUE, 'AQAAAAIAAYagAAAAEJ9fwqD60nfRFIDsqQNAgUA5L//w6rW3oCdBZ3F9vyUj+n9yg5uxZ6NhNKr9nFSJAA==', 'A7AYE46V5ZPK54TLROYCLZDZD3HGMKDQ', '7144748b-0c5d-49af-a59e-e3759243a156', '+34600000001', FALSE, FALSE, TRUE, 0, 'Admin', now()),
    (2, :'org', 'María', 'García', 'maria.garcia@reservarte.com', 'MARIA.GARCIA@RESERVARTE.COM', 'maria.garcia@reservarte.com', 'MARIA.GARCIA@RESERVARTE.COM', TRUE, 'AQAAAAIAAYagAAAAENWuldHEn9f0gfdTc5VJcxrXK8TulE3DhRJA8wVBEzcX8CU8RNTx7cqXqXWI92e2ZQ==', '5GXEUDADWVSWXKOM3TDCCRKCV7ZVAOVC', '6d38ef73-2223-47ad-976d-bdb2fdf0cf55', '+34600000002', FALSE, FALSE, TRUE, 0, 'Employee', now()),
    (3, :'org', 'Lucía', 'Martínez', 'lucia.martinez@reservarte.com', 'LUCIA.MARTINEZ@RESERVARTE.COM', 'lucia.martinez@reservarte.com', 'LUCIA.MARTINEZ@RESERVARTE.COM', TRUE, 'AQAAAAIAAYagAAAAEFhCwLkQrulXAFERzXr3koCGgnQ74Z+ybU71l9dR5HyaLXvGd5qWi+znJTBWxBe/IQ==', 'SDYQAPXHAMAA3NBX7M2LDZAXZOGOJW5Q', '98b47c35-0da7-4efc-9191-1736be2ee035', '+34600000003', FALSE, FALSE, TRUE, 0, 'Employee', now()),
    (4, :'org', 'Carmen', 'López', 'carmen.lopez@example.com', 'CARMEN.LOPEZ@EXAMPLE.COM', 'carmen.lopez@example.com', 'CARMEN.LOPEZ@EXAMPLE.COM', TRUE, 'AQAAAAIAAYagAAAAEIpf+2PwrKqGm+TkpYF+kB25tiQkhNjWyAxCMy5qDE8fBIjLJizzo1yyeD1p0MCPSw==', 'LF5EIFMGOLBAHHR4XLXI2LJ2MOV6UFM2', '622f982f-6ae3-4413-ac05-f153196d6ae0', '+34600000004', FALSE, FALSE, TRUE, 0, 'Customer', now()),
    (5, :'org', 'Sofía', 'Ruiz', 'sofia.ruiz@example.com', 'SOFIA.RUIZ@EXAMPLE.COM', 'sofia.ruiz@example.com', 'SOFIA.RUIZ@EXAMPLE.COM', TRUE, 'AQAAAAIAAYagAAAAEHdz3c0vLZhDNYlsW9mSrVb5aW4f9NyXPccM+cZGkI4paaZEiCoXxvL9fy3otWZ5WQ==', 'LI5VHQPUIFGV7CBI25UZG6A4CSH6WUZS', '898793f5-79ed-4f1d-8e74-bcf24231a270', '+34600000005', FALSE, FALSE, TRUE, 0, 'Customer', now()),
    -- Admin solo social (RA-869faedz3): PasswordHash NULL; la API le vincula Google por email.
    (6, :'org', 'Taker', 'Vare', 'takervare@gmail.com', 'TAKERVARE@GMAIL.COM', 'takervare@gmail.com', 'TAKERVARE@GMAIL.COM', TRUE, NULL, 'DAP22WCWPUTMHYC73MLQ3DNPPRQFIORV', '4efd7e35-191c-45a8-9e1b-878cb411cfb8', NULL, FALSE, FALSE, TRUE, 0, 'Admin', now());

-- ── Fichas de empleado (Id = Id de la cuenta) ────────────────────────────────
INSERT INTO "Employees" ("Id", "OrganizationId", "FirstName", "LastName", "Email", "Phone", "Rol", "HireDate", "IsActive", "CreatedAt")
VALUES
    (2, :'org', 'María', 'García', 'maria.garcia@reservarte.com', '+34600000002', 'Employee', '2024-03-01', TRUE, now()),
    (3, :'org', 'Lucía', 'Martínez', 'lucia.martinez@reservarte.com', '+34600000003', 'Employee', '2025-01-15', TRUE, now());

-- ── Horario semanal demo ─────────────────────────────────────────────────────
-- Convención del proyecto: 0 = lunes … 6 = domingo (RA-869d7ezrr). NO es
-- System.DayOfWeek, que empieza en domingo.
INSERT INTO "EmployeeAvailabilities" ("OrganizationId", "EmployeeId", "DayOfWeek", "StartTime", "EndTime", "IsRecurring", "IsActive", "CreatedAt")
VALUES
    (:'org', 2, 0, '09:00', '18:00', TRUE, TRUE, now()),  -- María, lunes
    (:'org', 2, 1, '09:00', '18:00', TRUE, TRUE, now()),  -- María, martes
    (:'org', 2, 2, '09:00', '18:00', TRUE, TRUE, now()),  -- María, miércoles
    (:'org', 2, 3, '09:00', '18:00', TRUE, TRUE, now()),  -- María, jueves
    (:'org', 2, 4, '09:00', '14:00', TRUE, TRUE, now()),  -- María, viernes
    (:'org', 3, 0, '10:00', '19:00', TRUE, TRUE, now()),  -- Lucía, lunes
    (:'org', 3, 1, '10:00', '19:00', TRUE, TRUE, now()),  -- Lucía, martes
    (:'org', 3, 2, '10:00', '19:00', TRUE, TRUE, now()),  -- Lucía, miércoles
    (:'org', 3, 3, '10:00', '19:00', TRUE, TRUE, now()),  -- Lucía, jueves
    (:'org', 3, 4, '10:00', '15:00', TRUE, TRUE, now());  -- Lucía, viernes

-- ── Fichas de clienta (Id = Id de la cuenta; RA-869d7f32r) ──────────────────
INSERT INTO "Customers" ("Id", "OrganizationId", "FirstName", "LastName", "Email", "Phone", "Category", "LoyaltyPoints", "IsBlocked", "PreferredContactMethod", "IsActive", "CreatedAt")
VALUES
    (4, :'org', 'Carmen', 'López', 'carmen.lopez@example.com', '+34600000004', 'vip', 0, FALSE, 'email', TRUE, now()),
    (5, :'org', 'Sofía', 'Ruiz', 'sofia.ruiz@example.com', '+34600000005', 'regular', 0, FALSE, 'email', TRUE, now());

-- Tratamiento de datos (obligatorio) para las dos; Carmen acepta además marketing.
INSERT INTO "CustomerConsents" ("OrganizationId", "CustomerId", "ConsentType", "IsGranted", "GrantedAt", "IsActive", "CreatedAt")
VALUES
    (:'org', 4, 'data_processing', TRUE, now(), TRUE, now()),
    (:'org', 4, 'marketing', TRUE, now(), TRUE, now()),
    (:'org', 5, 'data_processing', TRUE, now(), TRUE, now());

INSERT INTO "CustomerAllergies" ("OrganizationId", "CustomerId", "AllergyDescription", "Severity", "IsActive", "CreatedAt")
VALUES (:'org', 4, 'Látex', 'high', TRUE, now());

-- Nota interna escrita por María (EmployeeId 2).
INSERT INTO "CustomerNotes" ("OrganizationId", "CustomerId", "EmployeeId", "Note", "IsActive", "CreatedAt")
VALUES (:'org', 4, 2, 'Prefiere citas por la tarde.', TRUE, now());

-- ── Catálogo de servicios (RA-869d7f3z0) ────────────────────────────────────
-- Ids explícitos: las variaciones, tarifas y asignaciones los referencian.
INSERT INTO "ServiceCategories" ("Id", "OrganizationId", "Name", "Description", "Color", "DisplayOrder", "IsActive", "CreatedAt")
VALUES
    (1, :'org', 'Cejas', 'Diseño, tinte y mantenimiento de cejas.', '#8B5E3C', 0, TRUE, now()),
    (2, :'org', 'Pestañas', 'Lifting y extensiones de pestañas.', '#4C3A51', 1, TRUE, now());

-- El tinte exige prueba de alergia 48 h antes (vol. 1 §3.1.4).
INSERT INTO "Services" ("Id", "OrganizationId", "CategoryId", "Name", "Description", "DurationMinutes", "BasePrice", "RequiresAllergyTest", "AllergyTestHoursBefore", "IsActive", "CreatedAt")
VALUES
    (1, :'org', 1, 'Diseño de cejas', 'Diseño personalizado con medición y depilación.', 45, 25.00, FALSE, 48, TRUE, now()),
    (2, :'org', 1, 'Tinte de cejas', 'Tinte semipermanente.', 30, 18.00, TRUE, 48, TRUE, now()),
    (3, :'org', 2, 'Lifting de pestañas', 'Curvado y fijación con nutrición.', 60, 40.00, FALSE, 48, TRUE, now()),
    -- Servicios de ejemplo de la pantalla de reserva (RA-869fagpx9), los mismos que asegura DevSeeder.
    (4, :'org', 1, 'Laminado de cejas', NULL, 60, 45.00, FALSE, 48, TRUE, now()),
    (5, :'org', 1, 'Henna de cejas', NULL, 40, 22.00, FALSE, 48, TRUE, now()),
    (6, :'org', 2, 'Tinte de pestañas', NULL, 20, 15.00, FALSE, 48, TRUE, now());

-- Modificadores: se suman al servicio base, no lo sustituyen.
INSERT INTO "ServiceVariations" ("OrganizationId", "ServiceId", "Name", "PriceModifier", "DurationModifier", "IsActive", "CreatedAt")
VALUES (:'org', 1, 'Con hilo', 5.00, 15, TRUE, now());

-- Tarifas por nivel: precio final de cada nivel, no un recargo sobre el base.
INSERT INTO "ServicePricings" ("OrganizationId", "ServiceId", "EmployeeLevel", "Price", "IsActive", "CreatedAt")
VALUES
    (:'org', 1, 'junior', 22.00, TRUE, now()),
    (:'org', 1, 'senior', 25.00, TRUE, now()),
    (:'org', 1, 'expert', 30.00, TRUE, now());

-- Quién sabe hacer qué (tabla puente EmployeeServices; clase
-- EmployeeServiceAssignment, RA-869f17y7n). Destreza de 1 a 5.
-- IsActive explícito: las columnas de este esquema no llevan DEFAULT en base de
-- datos (lo pone la entidad), y aquí no hay entidad de por medio.
INSERT INTO "EmployeeServices" ("OrganizationId", "EmployeeId", "ServiceId", "ProficiencyLevel", "IsActive")
VALUES
    (:'org', 2, 1, 5, TRUE),  -- María, diseño de cejas
    (:'org', 2, 2, 4, TRUE),  -- María, tinte
    (:'org', 2, 3, 3, TRUE),  -- María, lifting
    (:'org', 3, 1, 3, TRUE),  -- Lucía, diseño de cejas
    (:'org', 3, 2, 4, TRUE),  -- Lucía, tinte
    (:'org', 2, 4, 3, TRUE),  -- María, laminado
    (:'org', 2, 5, 3, TRUE),  -- María, henna
    (:'org', 3, 5, 3, TRUE),  -- Lucía, henna
    (:'org', 3, 6, 3, TRUE);  -- Lucía, tinte de pestañas

-- ── Secuencias tras los Ids explícitos ───────────────────────────────────────
-- Sin esto, la primera alta de la API intentaría el Id 1 y chocaría.
SELECT setval(pg_get_serial_sequence('"AspNetUsers"', 'Id'), (SELECT max("Id") FROM "AspNetUsers"));
SELECT setval(pg_get_serial_sequence('"ServiceCategories"', 'Id'), (SELECT max("Id") FROM "ServiceCategories"));
SELECT setval(pg_get_serial_sequence('"Services"', 'Id'), (SELECT max("Id") FROM "Services"));

COMMIT;

\echo Datos demo insertados en la base :db.
\endif
