<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ReservArte_API</RootNamespace>
    <UserSecretsId>5665626b-335c-4bbf-9030-441c0e61b3a8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWS.Logger.SeriLog" Version="4.0.2" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReservArte-Application\ReservArte.Application.csproj" />
    <ProjectReference Include="..\ReservArte-Infrastructure\ReservArte.Infrastructure.csproj" />
    <ProjectReference Include="..\ReservArte-Shared\ReservArte.Shared.csproj" />
  </ItemGroup>

</Project>
